jobs:
  build:
    env:
      MAVEN_OPTS: -Xmx1024M
    permissions:
      contents: read
      pull-requests: read
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        cache: maven
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      if: ${{ matrix.os == 'windows-latest' }}
      name: Build with Apache Maven (Windows)
      run: mvn -U clean install -fae -B -Peverything
    - continue-on-error: true
      if: ${{ matrix.os != 'windows-latest' }}
      name: Build with Apache Maven
      run: mvn -U clean install -Djava.awt.headless=true -fae -B -Peverything
    strategy:
      matrix:
        os:
        - windows-latest
        - ubuntu-latest
    timeout-minutes: 130
name: Build and Test
on:
  repository_dispatch:
    types: trigger-ga___pull-request-build.yml
permissions:
  contents: read
